on:
  push:
    branches:
    - main
    - release/*
    tags:
    - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-custom-packages:
    name: Build Custom Packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Prerequisites
      working-directory: custom/ghidra
      run: |
        sudo apt-get build-dep -y .
        sudo apt install -y wget

    - name: Download Ghidra
      working-directory: custom/ghidra
      run: ./get-ghidra.sh
    - name: Build Ghidra Package
      working-directory: custom/ghidra
      run: dpkg-buildpackage -b --no-sign


    - name: Build snapper-extra-config Package
      working-directory: custom/snapper-extra-config
      run: dpkg-buildpackage -b --no-sign

    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: custom/*.deb

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          custom/*.deb
